
/* #!
 * Copyright (c) 2026 Adel'gid Aragami
 *
 * Licensed under the BSD 2-Clause License.
 * See the LICENSE file in the project root for more details.
 *
 * Source : https://github.com/Adel-gid/MASTER
 !# */

#ifndef MASTER_zzz_TCC_CONFIG_H
#define MASTER_zzz_TCC_CONFIG_H

#include <master_enum.h>

#if !defined(MASTER_zzz_COMPILER_FEATURES_LOADED) && !defined(MASTER_NO_COMPILER_FEATURES)

MASTER_BEGIN_DECLARATIONS

#define MASTER_COMPILER_SIZEOF_CHAR 1
#define MASTER_COMPILER_SIZEOF_SHORT 2
#define MASTER_COMPILER_SIZEOF_INT 4
#define MASTER_COMPILER_SIZEOF_LONG 4
#define MASTER_COMPILER_SIZEOF_LONG_LONG 8
#define MASTER_COMPILER_SIZEOF_SIZE_T 8

#define MASTER_LIBRARY_HAVE_COMPLEX_H 0
#define MASTER_LIBRARY_HAVE_ISO646_H 0
#define MASTER_LIBRARY_HAVE_TGMATH_H 0
#define MASTER_LIBRARY_HAVE_IMM_H 0
#define MASTER_LIBRARY_HAVE_WINNETWK_H 0
#define MASTER_LIBRARY_HAVE_WINNLS_H 0
#define MASTER_LIBRARY_HAVE_WINSVC_H 0
#define MASTER_LIBRARY_HAVE_CDERR_H 0
#define MASTER_LIBRARY_HAVE_COMMLDG_H 0
#define MASTER_LIBRARY_HAVE_DDE_H 0
#define MASTER_LIBRARY_HAVE_DDEML_H 0
#define MASTER_LIBRARY_HAVE_DLGS_H 0
#define MASTER_LIBRARY_HAVE_LZEXPAND_H 0
#define MASTER_LIBRARY_HAVE_MMSYSTEM_H 0
#define MASTER_LIBRARY_HAVE_NB3MASTER_ANSWER_N_H 0
#define MASTER_LIBRARY_HAVE_RPC_H 0
#define MASTER_LIBRARY_HAVE_SHELLAPI_H 0
#define MASTER_LIBRARY_HAVE_WINCRYPT_H 0
#define MASTER_LIBRARY_HAVE_WINPERF_H 0
#define MASTER_LIBRARY_HAVE_WINRESRC_H 0
#define MASTER_LIBRARY_HAVE_WINSOCK_H 0
#define MASTER_LIBRARY_HAVE_WINSPOOL_H 0
#define MASTER_LIBRARY_HAVE_WINBGIM_H 0
#define MASTER_LIBRARY_HAVE_OLE2_H 0
#define MASTER_LIBRARY_HAVE_OBJBASE_H 0
#define MASTER_LIBRARY_HAVE_OLEAUTO_H 0
#define MASTER_LIBRARY_HAVE_OLETLID_H 0
#define MASTER_COMPILER_SIMD_USES 0
#define MASTER_COMPILER_WARNING_AVAIL 1

#define MASTER_zzz_COMPILER_FEATURES_LOADED 1

MASTER_END_DECLARATIONS

#endif /* #! Compiler features !# */

#ifdef MASTER_LAST_LINE_LIBRARY_NUMBERS
	const unsigned int MASTER_zzz_TCC_CONFIG_H_LLINE = MASTER_LINE + 6;
#endif /* #! MASTER_LAST_LINE_LIBRARY_NUMBERS !# */

#endif /* #! MASTER_zzz_TCC_CONFIG_H !# */

/* #! be master~ !# */
